//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {

        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        [Range(18, 99)]
        public int Edad { get; set; }

        [Required]
        public string Carrera { get; set; }

        [Range(1, 25)]
        [Required]
        public int Cuatrimestre { get; set; }
    }
}
